private = { ignore = true }
accepted = [
    "MIT",
    "BSL-1.0",
    "Zlib",
    "BSD-3-Clause",
    "Apache-2.0",
    "MPL-2.0",
]
ignore-build-dependencies = true
ignore-dev-dependencies = true

[bstr.clarify]
license = "MIT OR Apache-2.0"

[[bstr.clarify.files]]
path = "LICENSE-APACHE"
license = "Apache-2.0"
checksum = "a60eea817514531668d7e00765731449fe14d059d3249e0bc93b36de45f759f2"

[[bstr.clarify.files]]
path = "LICENSE-MIT"
license = "MIT"
checksum = "6b7374c39a57e57fc2c38eb529c4c88340152b10f51dd5ae2d819dfa67f61715"

[typenum.clarify]
license = "MIT OR Apache-2.0"

[[typenum.clarify.files]]
path = "LICENSE-APACHE"
license = "Apache-2.0"
checksum = "516b24e051bf5630880ebbd55c40a25ce9552ebaf8970a53e8976eb70e522406"

[[typenum.clarify.files]]
path = "LICENSE-MIT"
license = "MIT"
checksum = "a825bd853ab71619a4923d7b4311221427848070ff44d990da39b0b274c1683f"
